# Generated by markup-carve/carve-rs .github/workflows/release.yml.
# Edits here are overwritten on the next release.
class Carve < Formula
  desc "Parser and renderer for the Carve markup language"
  homepage "https://markup-carve.github.io/carve/"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/markup-carve/carve-rs/releases/download/0.1.8/carve-0.1.8-aarch64-apple-darwin.tar.gz"
      sha256 "35f0ca8e34db39592081dd31ec5348ee616193f4c23bf2744dd1cd54b03342ca"
    end
    on_intel do
      url "https://github.com/markup-carve/carve-rs/releases/download/0.1.8/carve-0.1.8-x86_64-apple-darwin.tar.gz"
      sha256 "ed497dfcd76743d499eac5031af06b35af62494edbbcd09cdb50ba486a1530de"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/markup-carve/carve-rs/releases/download/0.1.8/carve-0.1.8-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "a0926e25dd6f91a48582931e73552412cc7f6c7139ebc70332757d021100ef98"
    end
    on_intel do
      url "https://github.com/markup-carve/carve-rs/releases/download/0.1.8/carve-0.1.8-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "c70bc90729a5d38b4c49104d26c80c0c6b628dd6cdb5d6ea37910af6b457825b"
    end
  end

  def install
    bin.install "carve"
  end

  test do
    assert_match "<h1", pipe_output(bin/"carve", "# Hello\n")
  end
end
