# Generated by markup-carve/carve-rs .github/workflows/release.yml.
# Edits here are overwritten on the next release.
class Carve < Formula
  desc "Parser and renderer for the Carve markup language"
  homepage "https://markup-carve.github.io/carve/"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/markup-carve/carve-rs/releases/download/0.1.4/carve-0.1.4-aarch64-apple-darwin.tar.gz"
      sha256 "70c197fa3cc8e21365498c6c7fe4687ff8e0e98d2b18e8c019ce9e7b3612a328"
    end
    on_intel do
      url "https://github.com/markup-carve/carve-rs/releases/download/0.1.4/carve-0.1.4-x86_64-apple-darwin.tar.gz"
      sha256 "e67e170274e6b2caa62a696e10ec6b406fe0279ec3dcdbbbdd845b03646c4c22"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/markup-carve/carve-rs/releases/download/0.1.4/carve-0.1.4-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "dd52e2d44d112a4bd70ebc4cf1925a6e39dad1c41ed0ff1da3f80e0c45c16d5b"
    end
  end

  def install
    bin.install "carve"
  end

  test do
    assert_match "<h1", pipe_output(bin/"carve", "# Hello\n")
  end
end
