# Generated by markup-carve/carve-rs .github/workflows/release.yml.
# Edits here are overwritten on the next release.
class Carve < Formula
  desc "Parser and renderer for the Carve markup language"
  homepage "https://markup-carve.github.io/carve/"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/markup-carve/carve-rs/releases/download/0.1.6/carve-0.1.6-aarch64-apple-darwin.tar.gz"
      sha256 "6c604c6a41c19bdf7613ea1a0ba8274aecfa3a7516a9e430b4669a7d54ce2faa"
    end
    on_intel do
      url "https://github.com/markup-carve/carve-rs/releases/download/0.1.6/carve-0.1.6-x86_64-apple-darwin.tar.gz"
      sha256 "f982a57baa29cd08a5888f25a17b93886d2adb6fe6c965d958055dc1c9cae635"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/markup-carve/carve-rs/releases/download/0.1.6/carve-0.1.6-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0871f6599c2da1e042cd0174ab51707061ed2c79be7e35ae5c45f9adf02d8e7a"
    end
    on_intel do
      url "https://github.com/markup-carve/carve-rs/releases/download/0.1.6/carve-0.1.6-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "50ce106b06370783dfb6191de59d3cc2a6272e489d31d88f4c0e10930990e7d1"
    end
  end

  def install
    bin.install "carve"
  end

  test do
    assert_match "<h1", pipe_output(bin/"carve", "# Hello\n")
  end
end
